version: '2'
services:
    cnam-calendar:
        container_name: scraper
        build:
            context: ./../
            dockerfile: ./devEnv/Dockerfile
        image: cal-scrap-app
        volumes:
            - ./../:/home/scraper/
            - ./vol/last/:/home/scraper/last/
            - ./vol/history/:/home/scraper/history/
        ports:
            - 5000:5000
        tty: true
    selenium:
        container_name: selenium
        image: selenium/standalone-firefox-debug
        ports: 
            - 4444:4444
            - 5901:5900
