version: '3.8'
services:
    cnam-calendar-dev:
        container_name: scraperDev
        build:
            context: .
            dockerfile: ./Dockerfile.dev
        image: scraper
        volumes:
            - ./../src/:/home/scraper/code/
            - ../volDev/last/:/home/scraper/last/
            - ../volDev/history/:/home/scraper/history/
        ports:
            - 5000:5000
        tty: true
    selenium-dev:
        container_name: seleniumDev
        image: selenium/standalone-firefox-debug
        ports: 
            - 4444:4444
            - 5901:5900
